#spring配置
spring:
  application:
    name: LearnRuoYi
    #redis配置
  redis:
    host: 192.168.126.150
    port: 6379
    password: 123321
    #数据库
  datasource:
    username: root
    url: jdbc:mysql://sh-cynosdbmysql-grp-mqgh9bvi.sql.tencentcdb.com:24829/jtsys
    password: 15168472629WDgh
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 10MB
  #邮件配置
  mail:

    host: smtp.qq.com
    port: 587
    username: 3230935352@qq.com
    password: wnklvrqmoigvdaif
    protocol: smtp
    properties:
      mail:
        stmp:
          auth: true
          ssl:
            enable: true
            socketFactory:
              class: com.sun.mail.util.MailSSLSocketFactory
              fallback: false
    default-encoding: utf-8
#服务端口配置
server:
  port: 8090
  #mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    #系统配置
learn:
  resource: D:/a
  #订单过期时间
  order-timeout: -5
